# Generated by Django 4.0.6 on 2022-08-17 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('querysetapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='School',
            new_name='Students',
        ),
    ]
