# Generated by Django 4.0.6 on 2022-08-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querysetapi', '0002_rename_school_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='city',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='students',
            name='marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='students',
            name='name',
            field=models.CharField(default='Unknown', max_length=15),
        ),
        migrations.AddField(
            model_name='students',
            name='roll',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
