# Generated by Django 4.0.6 on 2022-08-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querysetapi', '0003_students_city_students_marks_students_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=15)),
                ('emp_num', models.IntegerField(default=0, unique=True)),
                ('city', models.CharField(default='Unknown', max_length=20)),
                ('salary', models.IntegerField(default=0)),
                ('join_date', models.DateField()),
            ],
        ),
    ]
