# Generated by Django 4.0.6 on 2022-08-18 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querysetapi', '0005_students_enroll_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='enroll_date',
            field=models.DateTimeField(default='1888-01-01'),
        ),
    ]
