# Generated by Django 4.0.6 on 2022-08-27 14:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(default='UnKnown', max_length=30)),
                ('song_duration', models.IntegerField(default=0, max_length=50)),
                ('use', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
