# Generated by Django 4.0.6 on 2022-08-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('many2manyrelationships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='song_duration',
            field=models.IntegerField(default=0),
        ),
    ]
