# Generated by Django 4.0.6 on 2022-08-27 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('many2manyrelationships', '0002_alter_songs_song_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songs',
            old_name='use',
            new_name='user',
        ),
    ]
