# Generated by Django 4.0.6 on 2022-08-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(default='Unknows', max_length=50)),
                ('city', models.CharField(default='Unknows', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MyCenter',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('proxyinteritanceapp.examcenter',),
        ),
    ]
