# Generated by Django 4.0.6 on 2022-08-22 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecname', models.CharField(default='Unknown', max_length=50)),
                ('city', models.CharField(default='Unknown', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('examcenter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='multitableinheritance.examcenter')),
                ('name', models.CharField(default='Unknown', max_length=50)),
                ('roll', models.IntegerField(default='Unknown')),
            ],
            bases=('multitableinheritance.examcenter',),
        ),
    ]
