# Generated by Django 4.0.6 on 2022-08-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelinheritanceapp', '0002_contractor_teacher_student_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contractor',
            name='name',
            field=models.CharField(default='Unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='Unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='name',
            field=models.CharField(default='Unknown', max_length=30),
        ),
    ]
